FROM mcr.microsoft.com/playwright:v1.55.0-noble
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY worker ./worker
COPY tsconfig.json ./
ENV APPLICATION_MODE=PREPARE_ONLY
CMD ["npm","run","worker"]
