"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { BriefcaseBusiness,FileText,HelpCircle,LayoutDashboard,Play,Settings,ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Application,Job,Question } from "@/lib/types";

const demoJobs:Job[]=[
 {id:"demo-1",company:"Numberly",title:"Software Engineer Backend / Fullstack",contract_type:"Stage",location:"Paris · Hybride",source_url:null,match_score:98,status:"PREPARED",publication_date:"2026-09-12"},
 {id:"demo-2",company:"Powens",title:"Software Engineer Apprentice",contract_type:"Alternance",location:"Paris · Hybride",source_url:null,match_score:97,status:"PREPARED",publication_date:"2026-09-12"},
 {id:"demo-3",company:"Veepee",title:"Data Governance Engineer",contract_type:"Stage",location:"Saint-Denis",source_url:null,match_score:93,status:"PREPARED",publication_date:"2026-09-13"}
];
export function Dashboard(){
 const [tab,setTab]=useState("jobs"),[jobs,setJobs]=useState<Job[]>(()=>createClient()?[]:demoJobs),[apps,setApps]=useState<Application[]>([]),[questions,setQuestions]=useState<Question[]>([]),[loading,setLoading]=useState(()=>Boolean(createClient())),[message,setMessage]=useState("");
 const modal=useRef<HTMLDialogElement>(null); const supabase=useMemo(()=>createClient(),[]);
 async function load(){setLoading(true);if(!supabase){setJobs(demoJobs);setLoading(false);return}const [{data:j,error},{data:a},{data:q}]=await Promise.all([supabase.from("jobs").select("*").order("created_at",{ascending:false}),supabase.from("applications").select("*,jobs(company,title)").order("created_at",{ascending:false}),supabase.from("application_questions").select("*").order("created_at",{ascending:false})]);if(error)setMessage(error.message);setJobs(j||[]);setApps((a||[]) as Application[]);setQuestions(q||[]);setLoading(false)}
 useEffect(()=>{if(!supabase)return;void (async()=>{await load()})()},[supabase]);
 async function addJob(form:FormData){if(!supabase){setMessage("Mode démonstration : configurez Supabase pour enregistrer.");return}const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Connectez-vous à Supabase Auth avant d’ajouter une offre.");return}const company=String(form.get("company")),title=String(form.get("title"));const {error}=await supabase.from("jobs").insert({user_id:user.id,company,title,contract_type:form.get("contract_type"),location:form.get("location"),official_url:form.get("official_url"),source_url:form.get("official_url"),fingerprint:`${company}|${title}|${form.get("location")}`.toLowerCase(),status:"DISCOVERED"});if(error)setMessage(error.message);else{modal.current?.close();setMessage("Offre enregistrée.");await load()}}
 const prepared=jobs.filter(j=>j.status==="PREPARED").length,high=jobs.filter(j=>(j.match_score||0)>=80).length;
 return <main className="shell"><header className="top"><div className="brand"><div className="mark">JH</div><div><div className="eyebrow">AI Agent Hunter</div><h1>Job Hunter Control</h1><div className="muted">Pilotage sécurisé des candidatures de Yassine</div></div></div><span className="mode"><ShieldCheck size={14}/> PREPARE_ONLY</span></header>
 <section className="grid"><Metric label="Offres" value={jobs.length}/><Metric label="Score ≥ 80" value={high}/><Metric label="Préparées" value={prepared}/><Metric label="Questions bloquantes" value={questions.filter(q=>q.blocking&&!q.approved).length}/></section>
 <section className="layout"><nav className="card nav">{[["jobs",LayoutDashboard,"Offres"],["applications",BriefcaseBusiness,"Candidatures"],["documents",FileText,"Documents"],["questions",HelpCircle,"Questions"],["runs",Play,"Exécutions"],["settings",Settings,"Réglages"]].map(([id,Icon,label])=><button key={String(id)} className={tab===id?"active":""} onClick={()=>setTab(String(id))}><Icon size={16}/> {String(label)}</button>)}</nav>
 <div className="card">{message&&<p className={message.includes("enregistrée")?"alert":"error"}>{message}</p>}<div className="panel-head"><div><h2>{({jobs:"Pipeline des offres",applications:"Candidatures",documents:"Documents générés",questions:"Questions à valider",runs:"Journal d’exécution",settings:"Configuration"} as Record<string,string>)[tab]}</h2><p className="muted">Aucune soumission automatique tant que le mode sécurisé est actif.</p></div>{tab==="jobs"&&<div className="toolbar"><button className="btn secondary" onClick={()=>void load()}>Actualiser</button><button className="btn" onClick={()=>modal.current?.showModal()}>Ajouter une offre</button></div>}</div>
 {loading?<div className="empty">Chargement…</div>:tab==="jobs"?<Jobs jobs={jobs}/>:tab==="applications"?<Applications rows={apps}/>:tab==="questions"?<Questions rows={questions}/>:tab==="documents"?<Empty text="Les CV et lettres générés apparaîtront ici avec version et approbation."/>:tab==="runs"?<Empty text="Les recherches, préparations et pauses du worker apparaîtront ici."/>:<SettingsPanel configured={Boolean(supabase)}/>}</div></section>
 <dialog ref={modal}><form action={addJob} className="form"><div className="wide"><h2>Nouvelle offre</h2><p className="muted">Elle sera enregistrée comme DISCOVERED, sans candidature.</p></div><label>Entreprise<input name="company" required/></label><label>Poste<input name="title" required/></label><label>Contrat<select name="contract_type"><option>Alternance</option><option>Stage</option></select></label><label>Lieu<input name="location" defaultValue="Paris"/></label><label className="wide">URL officielle<input name="official_url" type="url"/></label><div className="wide toolbar"><button type="button" className="btn secondary" onClick={()=>modal.current?.close()}>Annuler</button><button className="btn">Enregistrer</button></div></form></dialog></main>
}
function Metric({label,value}:{label:string,value:number}){return <div className="card"><div className="muted">{label}</div><div className="metric">{value}</div></div>}
function Jobs({jobs}:{jobs:Job[]}){return jobs.length?<table><thead><tr><th>Entreprise / poste</th><th>Contrat</th><th>Lieu</th><th>Score</th><th>Statut</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.company}</strong><br/><span className="muted">{j.title}</span></td><td>{j.contract_type||"—"}</td><td>{j.location||"—"}</td><td className="score">{j.match_score??"—"}</td><td><span className={`status ${j.status.toLowerCase()}`}>{j.status}</span></td></tr>)}</tbody></table>:<Empty text="Aucune offre pour le moment."/>}
function Applications({rows}:{rows:Application[]}){return rows.length?<table><thead><tr><th>Entreprise / poste</th><th>Plateforme</th><th>Statut</th><th>Créée</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.jobs?.company||"—"}<br/><span className="muted">{a.jobs?.title}</span></td><td>{a.platform||"—"}</td><td><span className="status">{a.status}</span></td><td>{new Date(a.created_at).toLocaleDateString("fr-FR")}</td></tr>)}</tbody></table>:<Empty text="Aucune candidature enregistrée."/>}
function Questions({rows}:{rows:Question[]}){return rows.length?<table><thead><tr><th>Question</th><th>Catégorie</th><th>Réponse</th><th>Validation</th></tr></thead><tbody>{rows.map(q=><tr key={q.id}><td>{q.question}</td><td>{q.category}</td><td>{q.answer||"À confirmer"}</td><td><span className="status">{q.approved?"APPROUVÉE":"BLOQUANTE"}</span></td></tr>)}</tbody></table>:<Empty text="Aucune question en attente."/>}
function SettingsPanel({configured}:{configured:boolean}){return <div><p className="alert">Mode d’exécution : PREPARE_ONLY. Les CAPTCHA, MFA, déclarations légales et informations inconnues provoquent une pause obligatoire.</p><p>Supabase : <strong>{configured?"configuré":"variables absentes — aperçu démo"}</strong></p><p>Gemini : <strong>appel serveur uniquement</strong></p><p>Soumission automatique : <strong>désactivée</strong></p></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
