/**
 * Question catalogue.
 *
 * Every question the agent meets (generated by Gemini or found in an
 * application form) is mapped to a canonical `key`. Two questions that mean the
 * same thing ("Quelle est votre nationalité ?" / "Nationality") get the same key,
 * so an answer given once can be reused for every later application instead of
 * asking Yassine again.
 *
 * Pure functions only: this file is used by both the API routes and the
 * dashboard.
 */

export type AnswerType =
  | "text"
  | "textarea"
  | "select"
  | "boolean"
  | "date"
  | "ack";

export type QuestionSpec = {
  key: string;
  label: string;
  type: AnswerType;
  /** Choices offered to the user (select / boolean). */
  options?: string[];
  /** Adds an "Autre" choice with a free text box. */
  allowOther?: boolean;
  /** Legal / personal topic: never invented, always answered by the user. */
  sensitive?: boolean;
  /** Suggest remembering the answer for future applications. */
  remember: boolean;
  /** The answer has a validity date (residence permit...). */
  expires?: boolean;
  hint?: string;
};

export type IncomingQuestion = {
  question: string;
  category?: string | null;
  /** Options found on the real form (select / radio), when known. */
  options?: string[] | null;
  key?: string | null;
};

const YES_NO = ["Oui", "Non"];

export function normalizeText(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[’']/g, " ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

type Rule = { test: RegExp; spec: QuestionSpec };

/** Order matters: the first matching rule wins. */
const RULES: Rule[] = [
  {
    test: /\b(handicap|casier judiciaire|situation particuliere)\b/,
    spec: {
      key: "situation_particuliere",
      label: "Situation particulière (handicap, casier judiciaire)",
      type: "select",
      options: [
        "Je ne souhaite pas répondre",
        "Non concerné(e)",
        "Je souhaite en parler directement à l'employeur",
      ],
      allowOther: true,
      sensitive: true,
      remember: true,
      hint: "Sujet sensible : l'agent ne répond jamais à ta place.",
    },
  },
  {
    test: /\b(titre de sejour|permis de sejour|autorisation de travail|work permit|right to work|residence permit|work authori[sz]ation|visa)\b/,
    spec: {
      key: "titre_sejour",
      label: "Titre de séjour / autorisation de travail",
      type: "textarea",
      sensitive: true,
      remember: true,
      expires: true,
      hint: "Type exact, statut et date d'expiration. Une date de validité redemande la réponse quand elle expire.",
    },
  },
  {
    test: /\b(nationalite|nationality|citizenship)\b/,
    spec: {
      key: "nationalite",
      label: "Nationalité",
      type: "text",
      sensitive: true,
      remember: true,
    },
  },
  {
    test: /\b(e mail|email|courriel|adresse mail)\b/,
    spec: { key: "email", label: "E-mail", type: "text", remember: true },
  },
  {
    test: /\b(telephone|phone|portable|numero de mobile|mobile number)\b/,
    spec: { key: "telephone", label: "Téléphone", type: "text", remember: true },
  },
  {
    test: /\b(adresse|postal address|home address|code postal|domicile)\b/,
    spec: {
      key: "adresse",
      label: "Adresse postale",
      type: "text",
      remember: true,
    },
  },
  {
    test: /\b(convention de stage|convention|validation institutionnelle|school agreement)\b|\betablissement\b.*\b(exigences|repond)\b/,
    spec: {
      key: "convention_ecole",
      label: "Convention de stage / exigences de l'école",
      type: "select",
      options: ["Oui", "Non", "À vérifier avec mon école"],
      allowOther: true,
      remember: true,
    },
  },
  {
    test: /\b(pretentions|salaire|remuneration|salary|compensation)\b/,
    spec: {
      key: "pretentions_salariales",
      label: "Prétentions salariales",
      type: "text",
      sensitive: true,
      remember: false,
      hint: "Varie selon l'offre : non mémorisé par défaut.",
    },
  },
  {
    test: /\b(date de debut|date de demarrage|disponibilite|disponible a partir|start date|available from|availability|preavis)\b/,
    spec: {
      key: "disponibilite",
      label: "Disponibilité / date de début",
      type: "text",
      remember: true,
      expires: true,
    },
  },
  {
    test: /\b(duree du stage|duree du contrat|duree de l alternance|duration)\b/,
    spec: {
      key: "duree",
      label: "Durée souhaitée",
      type: "text",
      remember: true,
    },
  },
  {
    test: /\b(permis de conduire|driving licen[cs]e|vehicule)\b/,
    spec: {
      key: "permis",
      label: "Permis de conduire",
      type: "boolean",
      options: YES_NO,
      remember: true,
    },
  },
  {
    test: /\b(linkedin)\b/,
    spec: { key: "linkedin", label: "LinkedIn", type: "text", remember: true },
  },
  {
    test: /\b(github)\b/,
    spec: { key: "github", label: "GitHub", type: "text", remember: true },
  },
  {
    test: /\b(portfolio|site web|website|site personnel)\b/,
    spec: {
      key: "portfolio",
      label: "Portfolio / site web",
      type: "text",
      remember: true,
    },
  },
  {
    test: /\b(niveau d anglais|anglais|english level|english)\b/,
    spec: {
      key: "niveau_anglais",
      label: "Niveau d'anglais",
      type: "select",
      options: ["A2", "B1", "B2", "C1", "C2", "Langue maternelle"],
      allowOther: true,
      remember: true,
    },
  },
  {
    test: /\b(annees d experience|years of experience|experience professionnelle)\b/,
    spec: {
      key: "annees_experience",
      label: "Années d'expérience",
      type: "text",
      remember: true,
    },
  },
  {
    test: /\b(comment avez vous connu|how did you hear|source de candidature)\b/,
    spec: {
      key: "source_candidature",
      label: "Comment as-tu connu l'offre ?",
      type: "text",
      remember: true,
    },
  },
  {
    test: /\b(rgpd|donnees personnelles|consentement|consent|privacy|conditions generales|j accepte|je certifie|j atteste|declaration)\b/,
    spec: {
      key: "consentement_legal",
      label: "Consentement / déclaration légale",
      type: "select",
      options: ["J'accepte", "Je refuse"],
      sensitive: true,
      remember: false,
      hint: "Déclaration légale : jamais mémorisée, toujours confirmée à la main.",
    },
  },
  {
    test: /\b(motivation|pourquoi|why do you|why are you|why this|lettre de motivation)\b/,
    spec: {
      key: "motivation",
      label: "Motivation",
      type: "textarea",
      remember: false,
      hint: "Spécifique à chaque offre : non mémorisé.",
    },
  },
];

const HUMAN_CATEGORIES = new Set(["HUMAN_VERIFICATION", "UNKNOWN_FIELD"]);

const STOPWORDS = new Set(
  "le la les un une des de du d l et ou a au aux en dans pour par sur avec est etes etre vous votre vos quel quelle quels quelles que qui quoi ce cet cette ces il elle nous the of to and or in on for with is are your you what which do does did have has".split(
    " ",
  ),
);

function slug(text: string): string {
  const tokens = normalizeText(text)
    .split(" ")
    .filter((t) => t && !STOPWORDS.has(t));
  return tokens.slice(0, 8).join("_") || "question";
}

/** "Titre : la vraie question ?" → the part after the first colon. */
function stripPrefix(question: string): string {
  const idx = question.indexOf(":");
  const rest = idx > 0 && idx < 60 ? question.slice(idx + 1).trim() : "";
  return rest || question.replace(/:\s*$/, "").trim();
}

function inferType(text: string, options?: string[] | null): QuestionSpec["type"] {
  if (options && options.length) {
    const n = options.map(normalizeText).sort().join("|");
    return n === "non|oui" || n === "no|yes" ? "boolean" : "select";
  }
  const t = normalizeText(text);
  if (
    /^(avez vous|etes vous|souhaitez vous|acceptez vous|pouvez vous|do you|are you|have you|can you|would you)\b/.test(
      t,
    )
  )
    return "boolean";
  if (/\b(date|quand|when)\b/.test(t)) return "date";
  if (t.length > 160) return "textarea";
  return "text";
}

export function classifyQuestion(input: IncomingQuestion): QuestionSpec {
  const category = (input.category || "").toUpperCase();
  const options = input.options?.filter(Boolean) ?? undefined;

  if (HUMAN_CATEGORIES.has(category) || /^intervention humaine/i.test(input.question)) {
    return {
      key: input.key || `${category.toLowerCase() || "human"}_${slug(input.question)}`,
      label: input.question,
      type: "ack",
      remember: false,
      hint: "À faire toi-même dans le formulaire (CAPTCHA, MFA...). Marque comme traité ensuite.",
    };
  }

  const text = normalizeText(input.question);
  for (const rule of RULES) {
    if (rule.test.test(text)) {
      const fromForm = options && options.length ? options : undefined;
      return {
        ...rule.spec,
        options: fromForm ?? rule.spec.options,
        // The real form dictates the choices when it has its own list.
        allowOther: fromForm ? false : rule.spec.allowOther,
        type: fromForm && rule.spec.type !== "textarea" ? "select" : rule.spec.type,
      };
    }
  }

  const clean = stripPrefix(input.question);
  const type = inferType(clean, options);
  return {
    key: input.key || `custom_${slug(clean)}`,
    label: clean.length > 90 ? `${clean.slice(0, 87)}…` : clean,
    type,
    options: type === "boolean" && !options ? YES_NO : options,
    allowOther: false,
    remember: true,
  };
}

/**
 * Finds the option that corresponds to a remembered answer (or null).
 * `loose` also accepts "one contains the other" (only for long enough words,
 * so "Non" never matches "Non concerné(e)").
 */
export function matchOption(
  answer: string,
  options: string[],
  loose = true,
): string | null {
  const a = normalizeText(answer);
  if (!a) return null;
  const normalized = options.map((o) => [o, normalizeText(o)] as const);
  const exact = normalized.find(([, n]) => n === a);
  if (exact) return exact[0];
  if (!loose) return null;
  const partial = normalized.find(
    ([, n]) =>
      n && Math.min(n.length, a.length) >= 5 && (n.includes(a) || a.includes(n)),
  );
  return partial ? partial[0] : null;
}

export function isExpired(expiresAt: string | null | undefined, now = new Date()) {
  if (!expiresAt) return false;
  const d = new Date(expiresAt);
  return !Number.isNaN(d.getTime()) && d.getTime() <= now.getTime();
}

export type StoredAnswer = {
  question_key: string;
  answer: string;
  expires_at?: string | null;
};

/**
 * Decides whether a remembered answer can be reused for a question.
 * Returns the value to store (mapped onto the form's options if needed) or
 * null when the user must be asked again.
 */
export function reuseAnswer(
  spec: QuestionSpec,
  stored: StoredAnswer | undefined,
  now = new Date(),
): string | null {
  if (!stored || spec.type === "ack") return null;
  if (!stored.answer?.trim()) return null;
  if (isExpired(stored.expires_at, now)) return null;
  if (spec.options?.length && !spec.allowOther) {
    return matchOption(stored.answer, spec.options, !spec.sensitive);
  }
  return stored.answer;
}
